name: allo_urgence
description: Application de gestion des urgences hospitalières au Québec
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.2.0
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
